Resolves #2
CiscoSE/TalosBlacklistImporter pull request #3
Opened 2020-08-24 18:20 UTC by finchy

This Resolves issue #2.  Two additional things I'd like you to add.  A user-agent that identifies (in some way) the SW instance fetching the file, so we can see abusers.

2020-08-24 18:33 UTC, kyle-winters requested changes
Overall looks good. Just some minor changes needed before it can be merged. I will also change the name of the project to SnortBlockListImporter, and the python file to snort_block_list_importer. Please be sure to camelcase SnortBlockListImporter with a capital L

2020-08-24 18:33 UTC, kywinter commented on README.md
> +3. Run the script with ```python talos_block list_importer.py```
This will need to be fixed with new name and no spaces

2020-08-24 18:33 UTC, kywinter commented on README.md
> +- ```docker build -t snort-block_list-importer .```
please use either "-" or "_" but not both

2020-08-24 18:33 UTC, kywinter commented on README.md
> +- ```docker run -d --name snort-block_list-importer snort-block_list-importer```
please use either "-" or "_" but not both

2020-08-24 18:33 UTC, kywinter commented on talos_blacklist_importer.py
> +    """This is a function to run the main logic of the SnortBlock_listImporter"""
remove the underscore please

2020-08-24 18:47 UTC, finchy commented
Updated.

2020-08-25 00:28 UTC, kyle-winters approved these changes

2020-08-25 00:30 UTC, kywinter commented
It looks like I dont have write access required to merge the pull request. @TheAlanNix can you please give myself and/or Joel @finchy the necessary permissions please?

2020-08-25 00:40 UTC, finchy commented
I think Kyle should have permissions.  I don’t need them. 

Sent from my  iPhone

> On Aug 24, 2020, at 20:30, Kyle Winters <notifications@github.com> wrote:
> 
> ﻿
> It looks like I dont have write access required to merge the pull request. @TheAlanNix can you please give myself and/or Joel @finchy the necessary permissions please?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-25 01:29 UTC, TheAlanNix commented
It looks like an Owner in the CiscoSE organization needs to update the permissions on the repo - @cmlccie can you give @kywinter permissions on this repo?  If memory serves, I think I had sent a list of ~5 repos that he needed to be added to when I left back in May.

2020-08-25 01:30 UTC, merged

2020-08-25 02:33 UTC, kywinter commented
thanks @TheAlanNix, are you also able to rename the .py file to snort_block_list_importer.py and the project name to SnortBlocklistImporter please?